### ISSUE TITLE
"Something went wrong" popup error on config page

### ISSUE THREAD

**Issue by 130s** [pathec/ZWay-OpenHABConnector#3]
On OpenHAB Connector config view on the z-way app store (`http://RPI_IP:8083/smarthome/#/module/post/ZWay-OpenHABConnector`), I'm told "something went wrong" when pressing Save. No idea what's wrong. Any idea is appreciated.

Info typed in on the config view:
```
Enter a name for openHAB server: openHAB_server
Enter the openHAB server ip address: 192.168.0.28
Enter openHAB server port: 8080
```

I found a server log.
```
$ tail /var/log/z-way-server.log
:
[2017-06-17 16:15:15.285] [D] [zway] Job 0x05: deleted from queue
[2017-06-17 16:16:00.218] [I] [core] Notification: error (core): Cannot instantiate module: ZWay-OpenHABConnector: TypeError: undefined is not a function
[2017-06-17 16:16:00.256] [I] [core] TypeError: undefined is not a function
    at AutomationController.instantiateModule (automation/classes/AutomationController.js:395:24)
    at AutomationController.createInstance (automation/classes/AutomationController.js:851:23)
    at ZAutomationAPIWebRequest._.extend.createInstance (automation/ZAutomationAPIProvider.js:1138:40)
    at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/WebserverRequestRouter.js:259:41)
    at automation/WebserverRequestRouter.js:32:35
    at WebServer.document_root (automation/Webserver.js:35:11)
[2017-06-17 16:17:33.852] [I] [core] Notification: error (core): Cannot instantiate module: ZWay-OpenHABConnector: TypeError: undefined is not a function
[2017-06-17 16:17:33.861] [I] [core] TypeError: undefined is not a function
    at AutomationController.instantiateModule (automation/classes/AutomationController.js:395:24)
    at AutomationController.createInstance (automation/classes/AutomationController.js:851:23)
    at ZAutomationAPIWebRequest._.extend.createInstance (automation/ZAutomationAPIProvider.js:1138:40)
    at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/WebserverRequestRouter.js:259:41)
    at automation/WebserverRequestRouter.js:32:35
    at WebServer.document_root (automation/Webserver.js:35:11)
[2017-06-17 16:17:46.174] [I] [core] Notification: error (core): Cannot instantiate module: ZWay-OpenHABConnector: TypeError: undefined is not a function
[2017-06-17 16:17:46.185] [I] [core] TypeError: undefined is not a function
    at AutomationController.instantiateModule (automation/classes/AutomationController.js:395:24)
    at AutomationController.createInstance (automation/classes/AutomationController.js:851:23)
    at ZAutomationAPIWebRequest._.extend.createInstance (automation/ZAutomationAPIProvider.js:1138:40)
    at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/WebserverRequestRouter.js:259:41)
    at automation/WebserverRequestRouter.js:32:35
    at WebServer.document_root (automation/Webserver.js:35:11)
[2017-06-17 16:18:10.421] [I] [core] Notification: error (core): Cannot instantiate module: ZWay-OpenHABConnector: TypeError: undefined is not a function
[2017-06-17 16:18:10.432] [I] [core] TypeError: undefined is not a function
    at AutomationController.instantiateModule (automation/classes/AutomationController.js:395:24)
    at AutomationController.createInstance (automation/classes/AutomationController.js:851:23)
    at ZAutomationAPIWebRequest._.extend.createInstance (automation/ZAutomationAPIProvider.js:1138:40)
    at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/WebserverRequestRouter.js:259:41)
    at automation/WebserverRequestRouter.js:32:35
    at WebServer.document_root (automation/Webserver.js:35:11)
```

I git cloned `OpenHAB Connector`:
```
$ cd /opt/z-way-server/automation/userModules
$ git clone https://github.com/pathec/ZWay-OpenHABConnector.git
$ sudo git clone https://github.com/pathec/ZWay-OpenHABConnector.git
$ ll
total 16
drwxr-xr-x  3 root root 4096 Jun 17 16:05 ./
drwxrwxr-x 11 pi   pi   4096 Jun 16 20:08 ../
-rw-r--r--  1 root root    0 Jun 16 20:08 .keep
-rwxr-xr-x  1 root root  836 Jun 16 20:08 uploadModule.sh*
drwxr-xr-x  6 root root 4096 Jun 17 16:05 ZWay-OpenHABConnector/
$ ps -ef|grep z-way
$ sudo /etc/init.d/z-way-server restart
$ cd ZWay-OpenHABConnector/
pi@pi-desktop:/opt/z-way-server/automation/userModules/ZWay-OpenHABConnector$ git branch -vv
* master 4d656cc [origin/master] fix changelog
```
z-way ver (from http://RPI_IP:8083/smarthome/#/admin)
```
Software info
Firmware version	v2.3.4
UI version	1.7.0-RC-12
Built date	29-03-2017 15:36:36
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

$ apt-cache policy openhab2
openhab2:
  Installed: 2.0.0-1
  Candidate: 2.0.0-1
  Version table:
 *** 2.0.0-1 500
        500 https://dl.bintray.com/openhab/apt-repo2 stable/main armhf Packages
        100 /var/lib/dpkg/status
```

**Comment by 130s** [comment]
z-way ver (from http://RPI_IP:8083/smarthome/#/admin)
```
Software info
Firmware version	v2.3.4
UI version	1.7.0-RC-12
Built date	29-03-2017 15:36:36
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

$ apt-cache policy openhab2
openhab2:
  Installed: 2.0.0-1
  Candidate: 2.0.0-1
  Version table:
 *** 2.0.0-1 500
        500 https://dl.bintray.com/openhab/apt-repo2 stable/main armhf Packages
        100 /var/lib/dpkg/status
```
